
title: Max's Title
date: 2020-07-21



title: Max's learning page
author: Max learning github pages
email: Max@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Max's awesome description for learning github pages :D 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
